apiVersion: core.oam.dev/v1alpha2
kind: ScopeDefinition
metadata:
  name: healthscope.core.oam.dev
spec:
  allowComponentOverlap: true
  definitionRef:
    name: healthscope.core.oam.dev
---
apiVersion: core.oam.dev/v1alpha2
kind: HealthScope
metadata:
  name: example-health-scope